version: 2.1
  
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Create file 1
          background: true
          command: |
            echo "toto" | tee -a file1.txt
            echo "titi" | tee -a file2.txt
            
      - store_artifacts:
          path: /home/circleci/project/file1.txt
          destination: file1.txt
          
      - run:
          name: Nighty night
          command: sleep 3
     #     
     # - run:
     #     name: Do something.... anything!
     #     command: echo "Bah alors?!"
          
      - store_artifacts:
          path: /home/circleci/project/file2.txt
          destination: file2.txt
            
        
workflows:
  version: 2
  workflow:
    jobs:
      - build
