version: 2.1

parameters:
  run_bob:
    type: boolean
    default: false
  run_the:
    type: boolean
    default: false
  run_builder:
    type: boolean
    default: false


jobs:
  bob:
    docker:
      - image: circleci/python
      
    steps:
      - run:
          name: Can we
          command: |
            echo "Hello workflow ${CIRCLE_WORKFLOW_ID}"
            
  the:
    docker:
      - image: circleci/python
      
    steps:
      - run:
          name: It?
          command: |
            echo "Hello workflow ${CIRCLE_WORKFLOW_ID}"     
            
  builder:
    docker:
      - image: circleci/python
      
    steps:
      - run:
          name: It?
          command: |
            echo "Hello workflow ${CIRCLE_WORKFLOW_ID}"            
        
workflows:
  version: 2
  workflow-bob:
    when: << pipeline.parameters.run_bob >>
    jobs:
      - bob
      
  workflow-the:
    when: << pipeline.parameters.run_the >>
    jobs:
      - the
      
  workflow-builder:
    unless: << pipeline.parameters.run_bob >> || << pipeline.parameters.run_the >>
    jobs:
      - builder
