version: 2.1
jobs:
  build:
    docker:
      - image: openjdk:latest-alpine

    steps:
      - run:
          name: Install Docker client
          command: apk add docker-cli
          
      - run:
          name: Find docker
          command:  which docker
           
      - checkout

workflows:
  version: 2.1
  build:
    jobs:
      - build
