version: 2.1
  
jobs:
  build:
    machine: true
      
    steps:
      - run:
          name: Check buffer
          command: |
            default_gw=$(ip route show default|awk '{ print $3 }')
            echo $default_gw
            
        
workflows:
  version: 2
  workflow:
    jobs:
      - build
