version: 2.1
  
jobs:
  build:
    machine: true
      
    steps:
      - run:
          name: Check buffer
          command: |
            default_gw=$(netstat -r | grep default | awk '{ print $2 }')
            echo $default_gw
            ip route
            
        
workflows:
  version: 2
  workflow:
    jobs:
      - build
