version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node-browsers

    steps:         
      - run:
         name: Bundle version
         command: bundle version

      - checkout

workflows:
  version: 2.1
  build:
    jobs:
      - build
