version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node-browsers

    steps:
      - checkout
      - run:
         name: Bundle version
         command: bundle version
