version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Install GNUtls binaries
          command: |
            sudo apt-get update && sudo apt-get install gnutls-bin
      - run:
          name: Check GNUtls-cli version
          command: sudo gnutls-cli --version
