version: 2.1

commands:
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run:
          name: Greetings
          command: echo "Hello << parameters.to >>"
      
jobs:
  messer:
    parameters:
      tag-or-branch:
        description: Tag or Branch?
        type: env_var_name
        default: TAGANCH

    docker:
      - image: circleci/node
    steps:    
      - run:
          name: Tag or Branch
          command: |
              if [[ -z "<< pipeline.git.branch >>" ]]; then
                #echo "export TAGANCH=<< pipeline.git.tag >>" >> $BASH_ENV
                TAGANCH=<< pipeline.git.tag >>
                #else echo "export TAGANCH=<< pipeline.git.branch >>" >> $BASH_ENV
                else TAGANCH=<< pipeline.git.branch >>
              fi
              source $BASH_ENV

      - greeting:
          to: ${<< parameters.tag-or-branch >>}
          
workflows:
  welcome:
    jobs:
      - messer:
          filters:
            tags:
              only: /.*/
