version: 2.1

parameters:
  who-org:
    type: string
    default: ""

#### This is the forkeeeee

jobs:
  premier:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo job1
                   echo 'export << pipeline.parameters.who-org >>=$CIRCLE_USERNAME' >> $BASH_ENV
                   echo << pipeline.parameters.who-org >>
      
  deuxieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo job2
 
  troisieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum3
                                     
workflows:
  version: 2
  papa:
    when:
      equal: [ tech5irl, << pipeline.parameters.who-org >> ]
    jobs:
      - premier
          
  # papu:
  #  jobs:
  #    - premier
      
  tata:
    jobs:
      - deuxieme:
          context: Lecontext
  lala:
    jobs:
      - troisieme:
          context: Lecontext
