version: 2.1

orbs:
  detect: circleci/os-detect@0.3.0

commands: # a reusable command with parametersssssss
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run:
          name: Greetings
          command: echo "Hello <<parameters.to>>"
      
jobs:
  messer:
    parameters:
      expand:
        description: To whom shall we say hello??
        default: << pipeline.git.branch >>
        type: string
      
      laconditionouioui:
        description: La condition
        type: env_var_name
        default: condition_needed
        
      tag-or-branch:
        description: Tag or Branch?
        type: env_var_name
        default: TAGANCH
      
      laboule:
        default: true
        type: boolean
        
      switch:
        description: Allows to use the value of the env_var_name param in a logic statement
        type: env_var_name
        default: SWITCH_VAR
        
    docker:
      - image: circleci/node
    steps:
      - detect/init:
          extended: false
      - run :
          name: Second step
          command: |
              echo "Second step"
              #condition_needed_2=true
              #echo 'export condition_needed_2="true"' >> $BASH_ENV
              source $BASH_ENV
              #echo $condition_needed_2
              echo << parameters.laboule >>
              echo ${<< parameters.laconditionouioui >>}
              SWITCH_VAR=${<< parameters.laconditionouioui >>}
              echo <<parameters.switch >>
              
              
      - run:
          name: Tag or Branch
          command: |
              if [[ -z "<< pipeline.git.branch >>" ]]; then
                echo "export TAGANCH=<< pipeline.git.tag >>" >> $BASH_ENV
                #TAGANCH=<< pipeline.git.tag >>
                else echo "export TAGANCH=<< pipeline.git.branch >>" >> $BASH_ENV
                #else TAGANCH=<< pipeline.git.branch >>
              fi
              source $BASH_ENV
              echo ${<< parameters.tag-or-branch >>}
              echo ${<< parameters.laconditionouioui >>}
          
      - when:
          condition:
            equal: [ true, << parameters.switch >> ]
          steps:
            - run:
                name: Testing env_var_name interpolation
                command: |
                  echo $condition_needed_2
                  echo << parameters.laboule >>
                  echo "Second "
                  echo "step"
                  echo ${<< parameters.tag-or-branch >>}
                  echo ${<< parameters.laconditionouioui >>}
                  

      
      - greeting:
          to: ${<< parameters.tag-or-branch >>}
          
      - run :
          name: Third step
          command: |
              echo "Third "
              echo "step"
              echo << parameters.expand >>
              echo << pipeline.git.branch >>

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    jobs:
      - messer:
          filters:
            tags:
              only: /.*/

