version: 2.1

orbs:
  detect: circleci/os-detect@0.3.0

commands: # a reusable command with parametersssssss
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run:
          name: Greetings
          command: echo "Hello <<parameters.to>>"
      
jobs:
  messer:
    parameters:
      expand:
        description: "To whom shall we say hello??"
        default: "<< pipeline.git.branch >>"
        type: string
      
      laconditionouioui:
        type: env_var_name
        default: $condition_needed_2
        
      tag-or-branch:
        type: env_var_name
        default: "TAGANCH"
      
      laboule:
        default: true
        type: boolean
        
    docker:
      - image: circleci/node
    steps:
      - detect/init:
          extended: false
      - run :
          name: Second step
          command: |
              echo "Second step"
              #condition_needed_2=true
              #echo "export condition_needed_2=true" >> $BASH_ENV
              #source $BASH_ENV
              echo $condition_needed_2
              echo << parameters.laboule >>
              echo << parameters.laconditionouioui >>
              echo  << parameters.tag-or-branch >>
          
      - when:
          condition:
            equal: [ "true", << parameters.laconditionouioui >> ]
          steps:
            - run:
                name: Testing env_var_name interpolation
                command: |
                  echo $condition_needed_2
                  echo << parameters.laboule >>
                  echo "Second "
                  echo "step"
                  echo "export COND_EXP=<< parameters.laconditionouioui >>" >> $BASH_ENV
                  echo $COND_EXP
                  

      
      - greeting:
          to: << parameters.expand >>
          
      - run :
          name: Third step
          command: |
              echo "Second "
              echo "step"
              echo << parameters.expand >>
              echo << pipeline.git.branch >>

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    jobs:
      - messer
