version: 2.1

#### This is the forkeeeee

jobs:
  premier:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo job1
                   sleep 45
      
  deuxieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo job2
                   echo << pipeline.project.git_url >>
                   echo ${CIRCLE_USERNAME}
                   echo << pipeline.project.git_url >>
                                      
 
  troisieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum3
                                     
workflows:
  version: 2
  papa:
    when:
      equal: [ "https://github.com/yaningo/dockercli", << pipeline.project.git_url >> ]
     # equal: [ "tech5irl", ${CIRCLE_USERNAME} ]
    jobs:
      - premier
          
  # papu:
  #  jobs:
  #    - premier
  
  tata:
    jobs:
      - deuxieme
      
#  tata:
#    jobs:
#      - deuxieme:
#          context: Lecontext
  lala:
    jobs:
      - troisieme:
          context: Lecontext
