version: 2.1
jobs:
  build:
    docker:
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
      - image: redis:4
      
    steps:
      - run:
          name: Check buffer
          command: |
            redis-cli config get client-output-buffer-limit
        
workflows:
  version: 2
  workflow:
    jobs:
      - build
