version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  
jobs:
  build:
    docker:
      - image: circleci/python
      
    steps:
      - run:
          name: Check buffer
          command: |
            exit 1
            
        
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          post-steps: # steps to run after steps defined in the job bar
            - slack/status:
                mentions: "USERID1,USERID2" # Optional: Enter the Slack IDs of any user or group (sub_team) to be mentioned
              when: always

