version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node-browsers

    steps:
      - checkout
      - run:
         name: Bundle version
         command: bundle version
         
workflows:
  version: 2.1

  #################################################################
  #### DevOps
  #################################################################
  stop-microservices:
    triggers:
      - schedule:
          cron: "47 21 * * *"
          filters:
              branches:
                only:
                  - master
    jobs:
      - build
