version: 2.1
jobs:
  stuff:
   docker:
      - image: circleci/node
   steps:
      - run:
          name: Install redis tools
          command: |
            sudo apt-get install redis-tools ; while ! redis-cli ping 2>/dev/null ; do sleep 1 ; done
  
  build:
    docker:
      - image: redis:4

    steps:
      - run:
          name: Check buffer
          command: |
            redis-cli config get client-output-buffer-limit
        
workflows:
  version: 2
  workflow:
    jobs:
      - build
