version: 2.1
jobs:
  build:
    docker:
      - image: redis:4

    steps:
      - run:
          name: Check buffer
          command: config get client-output-buffer-limit
        
workflows:
  version: 2
  workflow:
    jobs:
      - build
