version: 2.1

executors:
  default:
    description: A debian-based machine executor
    machine: true

jobs:
  build:
    steps:
      - run:
         name: GNUtls version
         command: apt-cache search gnutls
         
workflows:
  version: 2.1
  start-microservices:
    jobs:
      - build
      
      
