version: 2.1
  
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Create file 1
          command: |
            echo "toto" | tee -a file1.txt
            
      - run:
          name: Create file 2
          command: |
            echo "titi" | tee -a file2.txt
            
      - store_artifacts:
          path: /home/circleci/project/file1.txt
          destination: file1.txt
          
      - run:
          name: Nighty night
          command: sleep 3
          
      - store_artifacts:
          path: /home/circleci/project/file2.txt
          destination: file2.txt
            
        
workflows:
  version: 2
  workflow:
    jobs:
      - build
