version: 2.1

#### This is the fork

jobs:
  premier:
    docker:
      - image: circleci/node
    
    steps:
      - run: |
          echo $CIRCLE_USERNAME
          if [ "$CIRCLE_USERNAME" = "tech5irl" ]; then
            circleci-agent step halt
          fi
         
          echo "Did I execute?"
      
  deuxieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo job2
 
  troisieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum3
                                     
workflows:
  version: 2
  papa: 
    jobs:
      - premier
          
  # papu:
  #  jobs:
  #    - premier
      
  tata:
    jobs:
      - deuxieme:
          context: Lecontext
  lala:
    jobs:
      - troisieme:
          context: Lecontext
