version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node-browsers

    steps:
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
         name: Find le petit Docker Client wih schedule
         command: which docker
         
      - run:
         name: Bundle version
         command: bundle version

      - checkout

workflows:
  version: 2.1
  build:
    jobs:
      - build
