# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  detect: circleci/os-detect@0.3.0

commands: # a reusable command with parameters
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run: echo "Hello <<parameters.to>>"
      
jobs:
  messer:
    parameters:
      expand:
        description: "To whom shall we say hello??"
        default: "<< pipeline.git.branch >>"
        type: string
      laconditionouioui:
        default: condition_needed
        type: env_var_name
        
    docker:
      - image: circleci/node
    steps:
      - detect/init:
          extended: false
      - run :
          name: Second step
          command: echo "Second step"
          
      - when:
          condition: << parameters.laconditionouioui >>
          steps:
            - run: echo << parameters.laconditionouioui >>
      
      - greeting:
          to: "<< parameters.expand >>"
          
      - run :
          name: Third step
          command: |
              echo "Second "
              echo "step"
              echo << parameters.expand >>
              echo << pipeline.git.branch >>

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    jobs:
      - messer
