version: 2.1
  
jobs:
  build:
    machine: true
      
    steps:
      - run:
          name: Install JDK 14
          command: |
            sudo add-apt-repository ppa:linuxuprising/java
            sudo apt update
            sudo apt install oracle-java14-installer
            java -version
            
workflows:
  version: 2
  workflow:
    jobs:
      - build
