version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python
      
    steps:
      - run:
          name: Check buffer
          command: |
            exit 222
            
        
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          post-steps: # steps to run after steps defined in the job bar
            - run:
                command: echo "Yes even when the job fails"

