version: 2.1
  
jobs:
  build:
    machine: true
      
    steps:
      - run:
          name: Install JDK 14
          command: |
            sudo apt-update && sudo apt-get install openjdk-14-jdk
            
        
workflows:
  version: 2
  workflow:
    jobs:
      - build
