version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python
      
    steps:
      - run:
          name: Follow project with API
          command: |
            curl -v -sS --fail -X POST https://circleci.com/api/v1.1/project/github/yaningo/setup-again/follow \
            --header "Circle-Token: $API_TOKI"
            
        
workflows:
  version: 2
  workflow:
    jobs:
      - build
