version: 2

#### This is the fork

jobs:
  premier:
    docker:
      - image: circleci/node
      
    - when:
        condition:
          - equal: [ yaningo, $CIRCLE_USERNAME ]
        steps:
           - run:
               command: |
                     echo job1
                   
  deuxieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo job2
 
  troisieme:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo jobnum3
                                     
workflows:
  version: 2
  papa:
    when:
      and: # All must be true to trigger
        - equal: [ master, << pipeline.git.branch >> ]
        
    jobs:
      - premier:
          context: Lecontext
          
  papu:
    jobs:
      - premier
      
  tata:
    jobs:
      - deuxieme:
          context: Lecontext
  lala:
    jobs:
      - troisieme:
          context: Lecontext
